### ISSUE TITLE
Add jQuery easing to navigation scroll

### ISSUE THREAD

**Issue by davidhjones** [codethesouth/website#19]
Use easeInOutExpo easing type

**Comment by codewithtyler** [comment]
Why do we need this?

**Comment by davidhjones** [comment]
I just think it looks better, but we can talk it over... I just added a issue to remind myself about it.

**Comment by davidhjones** [comment]
What are your thoughts?

**Comment by codewithtyler** [comment]
Most modern sites like [Code for America](https://www.codeforamerica.org/), [Microsoft](https://www.microsoft.com/en-us/), and [Apple](http://www.apple.com/) just use the browser's default scrolling feature. I'm not sure that this library really adds anything significant to the site to make it worth adding. For example, the toastr library added a notification system so the user knows if their message was successfully sent our not. This library just adds a scrolling animation, which to me isn't worth the extra KBs of code.

**Comment by davidhjones** [comment]
None of those websites have a single page scrolling functionality. I don't think you see what I'm trying to do. I'm not trying to hijack the ability to scroll the page, or use the mouse wheel. The functionality I'm suggesting is when you click on the navigation bar. Rather than have it jump to the section (like it was), I adding a scrolling animation (like sites like [Jatex](http://jatexinc.net/), and [SLAMR](http://preview.themeforest.net/item/slamr-ultimate-resume-and-personal-portfolio/full_screen_preview/7658524?_ga=1.57461992.390674883.1468856719)). Adding jQuery easing will allow to change the scrolling animation from linear to a different curve.

**Comment by codewithtyler** [comment]
Ok, then go for it. I'd just prefer to not add any more dependencies than we have to. Also while you're working on that what are your thoughts about adding Bootstrap scrollspy feature as well? It's already a dependency so nothing new would have to be added with that. We'd just need to add `data-spy="scroll"` to the opening body tag. We'd also need to add a data-target attribute as well I'm just not sure what we'd have to point it at for it to work.

**Comment by davidhjones** [comment]
scrollspy is cool, but it really do what I was talking about. Honestly, I think you're right. No reason to induce new dependencies without a huge need. I'll just leave the javascript animate property set as is, but not induce easing. (Honestly, that'll be better on us so we can call the website complete, and move on)
